---
title: Sounds for Pixels
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@soundsforpixels.com
description: |
  Want music that makes your game pop? Sound effects that brings your characters to life? Look no further: Sounds for Pixels are here to help!
baseurl: ''
url: soundsforpixels.com
twitter_username: soundsforpixels
instagram_username: soundsforpixels
github_username: TheHeartmann
markdown: kramdown
