# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sounds for Pixels
email: contact@soundsforpixels.com
description: > # this means to ignore newlines until "baseurl:"
  A music-making, game-playing duo. Here to help you make YOUR game stand out!
baseurl: "" # the subpath of your site, e.g. /blog
url: "soundsforpixels.com" # the base hostname & protocol for your site
twitter_username: soundsforpixels
instagram_username: soundsforpixels
github_username:  TheHeartmann

# Build settings
markdown: kramdown
